[build-system]
requires = ["setuptools>=42", "setuptools_scm[toml]>=3.4", "wheel"]

[tool.setuptools_scm]

[tool.pytest.ini_options]
addopts = "-k 'not spe1' --strict-markers"
markers = [
    "spe1"
]
