name: Create Doumentation Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version  }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: pip install -e .

      - name: Run Export
        run: |
          docs/export.py build/docs
          cat build/docs/ert-storage-api.html
          grep -q ensembles build/docs/ert-storage-api.html
