name: Publish

on:
  release:
    types: [published]

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build wheel
        run: |
          pip install --upgrade pip wheel setuptools
          pip wheel . --no-deps -w dist

      - name: Upload
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}

